### ISSUE TITLE
Composer install deletes airpress folder 

### ISSUE THREAD

**Issue by EliotNovel** [grgwrd/wordpress-starter#1]
Composer install deletes airpress folder in /web/wp-content/plugins

This issue can be solved by editing the composer.json file in line 39:
From section "preserve-paths":
Change from "web/wp-content/plugins/airtable"
To "web/wp-content/plugins/airpress"

**Comment by grgwrd** [comment]
@EliotNovel 

Thanks for pointing that out. Went ahead and updated the install path.
